### ISSUE TITLE
How to get resize line to show up

### ISSUE THREAD

**Issue by yashshah12** [gridgrid/grid-react-adapter#13]
Currently, I can manually resize my column and I see the hotpink draggable component but when I start dragging it, i dont see any indication of how much i am dragging it or where it is currently right now.

Is there a way to get that to display when i am resizing a column?

**Comment by scamden** [comment]
Are you including the default grid.scss that comes with the grid module?

**Comment by yashshah12** [comment]
Yes I am, I copied all of the grid.scss styles into my stylesheet

**Comment by yashshah12** [comment]
Also, in your example https://gridgrid.github.io/grid/, i dont see the column resize line showing when i try and resize a column

**Comment by scamden** [comment]
@yashshah12 just realized why you're not seeing it, the "hot pink" gave it away. you must be using grid v3. Grid react adapter is actually including the beta version of grid 4. It's technically in beta and could still have a few minor contract changes but it's nearly done so I think it's safe for you all to use. please try installing `grid@next` and use that style. (it's also MUCH prettier than that old junk :) )

**Comment by yashshah12** [comment]
Awesome. I took the styles from grid@4.4.0 and the grid resizing line showed up. Thanks

**Comment by scamden** [comment]
glad to hear it :) hope your eyes are burning a little less now as well :P
