### ISSUE TITLE
cellRenderer not being called

### ISSUE THREAD

**Issue by yashshah12** [gridgrid/grid-react-adapter#17]
I installed the latest package and headerCellRenderer seems to work fine but now cellRenderer is not being called.

this is my signature for the cellRenderer function `cellRenderer = ({ virtualCol: col, virtualRow: row, data }: IBuilderUpdateContext) => {}`

**Comment by scamden** [comment]
whoops you're totally right. the row builder was getting added to every row overriding the column one. fix building now

**Comment by scamden** [comment]
fixed in 2.0.1
