### ISSUE TITLE
When i update cols to include new hidden columns, the grid does not rerender

### ISSUE THREAD

**Issue by yashshah12** [gridgrid/grid-react-adapter#18]
I am implementing hiding and showing columns and when `cols` changes and I pass it into `<ReactGrid cols={cols}`, the grid doesnt rerender and show the new hidden or unhidden columns?

**Comment by scamden** [comment]
i have a feeling this is related to https://github.com/gridgrid/grid-react-adapter/issues/4. when you pass cols with the one of them set to hidden are they the same array reference as the last time you rendered by chance?

**Comment by yashshah12** [comment]
Yes, that was the issue. It works now. Closing this issue. :)

**Comment by scamden** [comment]
ok i'll still try to fix 18 so people don't have to magically know that the
reference cannot remain the same, but glad you got it working
