### ISSUE TITLE
Ability to select text from the grid

### ISSUE THREAD

**Issue by yashshah12** [gridgrid/grid-react-adapter#20]
I am trying to figure out why I cant seem to select text from a grid cell and copy it? I looked through the styles and see if `user-select` is set to none, but I cant seem to find it?

Do we have to use the copy-paste module? I just want the user to be able to highlight the text and use cmd+c to copy it to clipboard.

**Comment by scamden** [comment]
you can copy the text from whatever cell (or range of cells is selected).
it took a lot of work but cmd + c works for this :)

**Comment by scamden** [comment]
it also copies in tsv separated format so if you go paste into google
sheets or excel it will paste into the correct cell ranges.

**Comment by yashshah12** [comment]
i dont see the text highlighting when i try and copy the text. Can that be enabled through css

**Comment by scamden** [comment]
the text doesn't highlight because the focus cell highlight is meant to be
the indicator instead. otherwise when you drag across the cells to select
them you also get a text highlight that looks very un-grid like. if you go
check out google sheets they handle this case the same way.

**Comment by yashshah12** [comment]
Oh okay, i disabled the .grid-selection style but now I understand how it works now. 

Closing this as its not an issue

**Comment by scamden** [comment]
cool cool :_
