### ISSUE TITLE
Call LoadMoreRows on initial mount

### ISSUE THREAD

**Issue by yashshah12** [gridgrid/grid-react-adapter#22]
For an infinite scrolling use case, we might find it useful to use the same data loader regardless if we are in a scrolling state or initial state.

It would be particularly useful for restoring scroll state across renders.

**Comment by scamden** [comment]
i'm not sure i follow. the grid will call loadRows to fill the initial view even if you don't scroll

**Comment by yashshah12** [comment]
yes, you are right. Closing this as its not an issue
