### ISSUE TITLE
Making a column be fixed

### ISSUE THREAD

**Issue by yashshah12** [gridgrid/grid-react-adapter#23]
Is there a way to make a column be fixed like we can for rows?
Currently we can do ```rows[0].header=true```, is there an option to do the same for headers?

**Comment by scamden** [comment]
columns and rows can be set to `fixed` as well as `header` both result in the item being fixed the difference is whether it's considered in the data or not

**Comment by yashshah12** [comment]
so if we want the first column to be fixed, do we just do ```columns[0].fixed=true``` or do we have to pass in something else?

**Comment by scamden** [comment]
yep simple as that :)

**Comment by yashshah12** [comment]
It worked. Thanks

**Comment by scamden** [comment]
You got it :)
