### ISSUE TITLE
New API: default export

### ISSUE THREAD

**Issue by alexkrolick** [gridgrid/grid-react-adapter#7]
It doesn't look like there is any other export than `ReactGrid`, so this could probably be moved to the top level.

```diff
- import { ReactGrid } from 'grid-react-adapter'
+ import ReactGrid from 'grid-react-adapter'
```

**Comment by scamden** [comment]
i actually have a pet peeve about default exports. i don't think they add any value and just result in confusion when reading consuming code. they also result in a gross `require('grid-react-adapter').default` if you're not using modern import syntax. if you want to rename a named export you can always just use the alias syntax. the nice thing there is the original name remains in the import statement so finding usages of the lib is much easier.

**Comment by alexkrolick** [comment]
I think that confuses library consumers more than anything. Almost all libraries with a single export use default and CommonJS is on its way out this year with Node moving towards support for ESM.

The `*` import is also not equivalent to using default since it imports everything instead of just the default; for that reason named exports are typically used for optional/extra components.

**Comment by scamden** [comment]
I wasn’t suggesting * import. The alias syntax I mentioned is: import
{ReactGrid as Whatever} from ‘react-grid’;
